# Generated by Django 5.0.4 on 2024-04-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_rename_coord_pereval_coords_alter_level_autumn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pereval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.pereval'),
        ),
        migrations.DeleteModel(
            name='PerevalImages',
        ),
    ]
