# Generated by Django 5.0.4 on 2024-04-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_image_pereval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pereval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restapi.pereval'),
        ),
    ]
