# Generated by Django 5.0.4 on 2024-04-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_rename_user_pereval_adder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='adder',
            new_name='user',
        ),
    ]
